CREATE TABLE IF NOT EXISTS `#__shop_checkin` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`client_id` VARCHAR(255)  NOT NULL ,
`session_id` VARCHAR(255)  NOT NULL ,
`day` VARCHAR(255)  NOT NULL ,
`coordinates` VARCHAR(255)  NOT NULL ,
`checkin_time` VARCHAR(255)  NOT NULL ,
`checkin_place` TEXT NOT NULL ,
`checkout_time` VARCHAR(255)  NOT NULL ,
`checkout_place` TEXT NOT NULL ,
`comments` TEXT NOT NULL ,
`accompaniment` TEXT NOT NULL ,
`quality` VARCHAR(255)  NOT NULL ,
`created_on` DATETIME NOT NULL ,
`store` TEXT NOT NULL ,
`store_id` TEXT NOT NULL ,
`store_server_id` TEXT NOT NULL ,
`first_insert_date` VARCHAR(255)  NOT NULL ,
`last_sync_date` VARCHAR(255)  NOT NULL ,
`client_modified_date` DATETIME NOT NULL ,
`submitter` INT(11)  NOT NULL ,
`user_id` INT(11)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

