CREATE TABLE IF NOT EXISTS `#__brandstocks` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`brand` VARCHAR(255)  NOT NULL ,
`brandcode` VARCHAR(255)  NOT NULL ,
`currentstock` INT NOT NULL ,
`order_placed` VARCHAR(255)  NOT NULL ,
`orderplaced` INT NOT NULL ,
`order_date` DATE NOT NULL ,
`lpo_number` VARCHAR(255)  NOT NULL ,
`delivered` VARCHAR(255)  NOT NULL ,
`sale` VARCHAR(255)  NOT NULL ,
`stockout` INT NOT NULL ,
`submitter` INT(11)  NOT NULL ,
`client_id` INT NOT NULL ,
`stockdate` DATETIME NOT NULL ,
`store_id` TEXT NOT NULL ,
`store_server_id` TEXT NOT NULL ,
`client_modified_date` DATETIME NOT NULL ,
`store` TEXT NOT NULL ,
`remarks` TEXT NOT NULL ,
`coordinates` VARCHAR(255)  NOT NULL ,
`created` DATETIME NOT NULL ,
`first_insert` TIMESTAMP NOT NULL ,
`server_modified_date` DATETIME NOT NULL ,
`last_sync_date` VARCHAR(255)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

